### PR TITLE
Improve request list design

### PR DESCRIPTION
**Pull request by rdubigny**
connects to https://github.com/betagouv/api-particulier/issues/119

### CODE REVIEW

**Comment by giglemad** [comment]
I do not agree with putting this logic into the back. The backend is not responsible for display logic in front even if it is a back for front imho. Moreover we should not have to re-deploy our whole backend to correct some display sugar. Can we get this hash into the front app ?

**Comment by rdubigny** [comment]
@giglemad we will merge that for now, do not hesitate to suggest a better solution.

**Comment by giglemad** [comment]
I am still stronly against this. I don't see how it leads to having it twice in the frontend, since u could just have a decorator around enrollment object that would gather all of the display tweaks logic. This solution is burdening the back end for no good reason and makes front end updates dependant on back end deployments which is a really bad practice and should be reserved to multi language data bits that are changing a lot.

**Comment by rdubigny** [comment]
@giglemad it will be removed in https://github.com/betagouv/signup.api.gouv.fr-back/pull/58

After refactoring the front end we do not have the duplication issue anymore.

**Comment by giglemad** [comment]
Perfect

Cordialement

Hugo pour API Entreprise
https://entreprise.api.gouv.fr
https://entreprise.api.gouv.fr/documentation
https://dashboard.entreprise.api.gouv.fr


2018-06-28 18:42 GMT+02:00 Raphaël Dubigny <notifications@github.com>:

**Pull request merged**
